config/routes.rb
Rails.application.routes.draw do
  get 'cocktails/index'
  get 'cocktails/new'
  get 'cocktails/create'
  get 'cocktails/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :cocktails, only: [ :index, :show, :new, :create ] do
    resources :doses, only: [ :new, :create]
  end
  resources :doses, only: [ :destroy ]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord

  has_one_attached :photo

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :photo, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, :cocktail, :ingredient, presence: true
  validates_uniqueness_of :cocktail, :scope => [:ingredient]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  private
    def cocktail_params
      params.require(:cocktail).permit(:name, :photo)
    end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'cocktails/show'
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

app/views/cocktails/index.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://thumbs.dreamstime.com/b/cocktail-icon-logo-modern-line-style-high-quality-black-outline-pictogram-web-site-design-mobile-apps-vector-83611670.jpg" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Create a cocktail", cocktails_new_path, class: 'btn btn-primary' %>
      </li>
    </ul>
  </div>
</div>


<ul class="cards">
  <% @cocktails.each do |cocktail| %>
    <li>

      <div class="cards">

        <div class="card" style="width: 18rem;">
          <% if cocktail.photo.attached? %>
            <%= cl_image_tag cocktail.photo.key, class: "card-img-top" %>
          <% end %>
          <div class="card-body">
            <h5 class="card-title"> <%= link_to cocktail.name, cocktail_path(cocktail) %> </h5>
                <% cocktail.doses.each do |dose| %>
                    <%=  dose.ingredient.name %>
                <% end %>
          </div>
        </div>

      </div>


    </li>
  <% end %>
</ul>

app/views/cocktails/new.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/cocktails/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @cocktail.photo.key %>')">
  <div class="container">
    <h1><%= @cocktail.name %></h1>
    <p>
      <% @cocktail.doses.each do |dose| %>
        <li class="white"> <%= dose.description %> (Ingredient: <%=  dose.ingredient.name %>) <%= link_to dose_path(dose), method: :delete do %> <i class="fas fa-trash-alt"></i> <% end %> </li>
      <% end %>
    </p>
  </div>
</div>

<br>



<div class="form">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8">
      <h2> Add a dose </h2>
      <%= simple_form_for [ @cocktail, @dose ] do |f| %>
        <%= f.input :description %>
        <%= f.association :ingredient, include_blank: false %>
        <%= f.submit "Submit", class: "btn btn-primary" %>
      <% end %>
      <br>
      <%= link_to("See all cocktails", cocktails_path) %>
   </div>
  </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>